class GluttonyKeywords:

    unhealthfood = [

        "burrito",
        "chips",
        "fries",
        "hamberger",
        "hot dog",
        "nacho",
        "nugget",
        "onion rings",
        "pizza",
        "sandwich",
        "sausage",
        "taco"
        "bacon",
        "beef",
        "chicken",
        "duck",
        "ham",
        "mutton",
        "pork",
        "sausage",
        "steak",
        "turkey",
        "veal",
        "venison",
        "Barbados",
        "cherry juice",
        "cake",
        "base",
        "camelina",
        "oil",
        "castor",
        "broth",
        "chocolate",
        "covering",
        "chopped",
        "tomatoes",
        "crust",
        "duxelles",
        "false flax oil",
        "filling",
        "flan case",
        "hazelnutbutter",
        "hot water crust pastry",
        "inulin",
        "mashed tomatoes",
        "partly finished good",
        "patato flakes",
        "Puerto - Rican cherry juice",
        "puff pastry",
        "semi - finished goods",
        "translucent",
        "vegetable stock",
        "West Indies cherry",
        "wheatmeal porridge",
        "won ton wrappers",
        "almond oil",
        "apricotkernel oil",
        "argan oil",
        "baking oil",
        "bean oil",
        "beurre",
        "manié",
        "buttered",
        "camelina oil",
        "canola oil",
        "castor oil",
        "coconut oil",
        "cold - pressed olive oil",
        "corn oil",
        "cotton oil",
        "Damask rose oil",
        "dende",
        "edible oil",
        "eucalyptus oil",
        "evening primrose oil",
        "false flax oil",
        "fish oil",
        "flour - and -butter paste",
        "germ oil",
        "grape seed oil",
        "grape - stone oil",
        "groundnut oil",
        "hazelnut oil",
        "hemp oil",
        "jojoba oil",
        "Kazanlik rose oil",
        "kneaded butter",
        "knob of butter",
        "lear oil",
        "linseed oil",
        "lump of butter",
        "makadamianut oil",
        "Mazola RightBlend",
        "melted fat",
        "milk fat",
        "mustard oil",
        "noisette butter",
        "nuts oil",
        "oil",
        "olive oil",
        "palm oil",
        "passionflower seed oil",
        "peanut oil",
        "pecan oil",
        "rendered fat",
        "salted butter",
        "aspartame",
        "bar sugar",
        "Barbados Sugar",
        "beet sugar",
        "black molasses",
        "black treacle",
        "blackstrap",
        "blood sugar",
        "brown candy sugar",
        "brown sugar",
        "candy",
        "candy sugar",
        "cane sugar",
        "caster sugar",
        "churned honey",
        "clover honey",
        "coars sugar",
        "coffee crystals",
        "coffee sugar",
        "comb honey",
        "confectioner's sugar",
        "corn syrup",
        "cremed honey",
        "crystals",
        "cube sugar",
        "dark brown sugar",
        "demerara sugar",
        "dextrose",
        "French sugar",
        "fructose",
        "fruit sugar",
        "glucose",
        "golden syrup",
        "granulated sugar",
        "grape sugar",
        "grind",
        "candy",
        "grind candy",
        "gur",
        "heather honey",
        "honey fondant",
        "honeycomb (beehive)",
        "icing sugar",
        "invert sugar",
        "isomalt",
        "jaggery",
        "jam sugar",
        "corn syrup",
        "light brown sugar",
        "lime - tree honey",
        "lump sugar",
        "malt extract",
        "malt sugar",
        "malt syrup",
        "maple butter",
        "maple cream",
        "maple spread",
        "maple sugar",
        "maple syrup",
        "mascobado",
        "mascobado sugar",
        "moist brown sugar",
        "molasses",
        "muscovade",
        "nectar",
        "pear sugar",
        "powdered sugar",
        "preserving sugar",
        "rape honey",
        "rice syrup",
        "saccharin",
        "saccharine",
        "set honey",
        "simple syrup",
        "soft brown sugar",
        "soft sugar",
        "Spun© honey",
        "stevia",
        "stock syrup",
        "sugar",
        "sugar beet",
        "sugar cube",
        "hail",
        "sugar loaf",
        "sugar millet",
        "sugar replacer",
        "sugar syrup",
        "superfine granulated",
        "sweet sorghum",
        "sweetener",
        "treacle",
        "unrefined sugar",
        "whipped honey",
        "white caster sugar",
        "white sugar",
        "yellow sugar",
        "Yinnie syrup",
        "agar",
        "arrowroot",
        "aspic",
        "binder",
        "gf",
        "gluten-free",
        "instant flour",
        "jelly",
        "continuation",
        "kuzu",
        "seaweed isingglass",
        "thicken means",
        "thickening agent",
        "transparent jelly",
        "acorn cocoa",
        "baker's chocolate",
        "bitter(-sweet) chocolate",
        "carob",
        "chocolat sprinkles",
        "chocolate bar",
        "chocolate coating",
        "chocolate covering",
        "chocolate icing paste",
        "chocolate spread",
        "chocolate tablet",
        "Chocolate topping",
        "chocolate vermicelli",
        "coating chocolate",
        "cocoa",
        "cocoa - butter",
        "couverture",
        "covering chocolate",
        "dark chocolate",
        "flaked chocolate",
        "instant cocoa powder",
        "milk chocolate",
        "plain chocolate",
        "stuffed chocolate",
        "white chocolate",
        "butter",
        "butteroil",
        "clarified butter",
        "coconut fat",
        "colza oil",
        "compound butter",
        "copha fat",
        "dry white",
        "flavoured butter",
        "frying fat",
        "frying oil",
        "frying - butter",
        "ghee",
        "herb butter",
        "lard",
        "liquid margarine",
        "acerola",
        "alkekengi",
        "American blueberry",
        "arctic bramble",
        "arctic bramble",
        "arctic raspberry",
        "Austrian yellow-cress",
        "azarole",
        "azerolier fruit",
        "bake-apple berries",
        "bayberry fruit",
        "bigarreau",
        "bilberries",
        "black currants",
        "black currants",
        "blackberries",
        "blackthorn plum",
        "Blaeberry",
        "blueberries",
        "bocksdorn berry",
        "bog bilberries",
        "bog bilberry",
        "bog cranberry",
        "aitchbone",
        "beef chuck",
        "beef for braising",
        "beef sausage",
        "beef's first neck",
        "beef's fore ribs",
        "beefsteak",
        "blade",
        "blade bone",
        "bread kebab",
        "brisket",
        "brisket",
        "butcher's steak",
        "chuck",
        "clod",
        "corned - beef",
        "doner Kebab",
        "edgebone",
        "entrecote",
        "eye of round"
        "filet mignon",
        "fillet of beef",
        "fillet steak",
        "fillet steak beef",
        "flank",
        "flank steak",
        "french stew",
        "ground beef",
        "hanger steak",
        "hock",
        "insides",
        "kebab",
        "knuckle",
        "lamb kebab"
        "loin",
        "lowerribs",
        "marrow",
        "minced beef",
        "minced meat",
        "beef and pork",
        "osso buco",
        "ossobuco",
        "ox - tongue",
        "oxtail",
        "pony - bockrib",
        "pork ribs",
        "prime rib",
        "rib of beef",
        "ribs of beef",
        "roast beef",
        "roasting joint",
        "rump",
        "rump cap",
        "rumpsteak",
        "salmon cut",
        "shank",
        "shank of veal",
        "shin",
        "silverside",
        "sirloin",
        "sirloin",
        "skirt steak",
        "steak",
        "stew meat",
        "stewed steak",
        "stewing steak",
        "striploin",
        "tenderloin",
        "thin flank",
        "topsides",
        "tournedos",
        "undercut steak",
        "veal ribs",
        "weanling",
        "calf tongue",
        "calf's meat",
        "fricandeau",
        "ossobuco",
        "piece of leg of veal",
        "shank of veal",
        "sweetbread",
        "sweetbread gland",
        "continuation",
        "thick flank",
        "veal breast",
        "veal collop",
        "veal cutlet",
        "veal fricassé",
        "veal fricassee",
        "veal scallop",
        "veal tongue",
        "continuation",
        "veal's neck",
        "veal's piece of leg",
        "veal",
        "veal meat",
        "weanling",
        "alpine chamois",
        "ardenne ham",
        "bacon",
        "boiled ham",
        "carcass",
        "chamois",
        "cheek",
        "chicken thigh",
        "chine",
        "chop",
        "coburger ham",
        "cubes of bacon",
        "cured meat",
        "cutlet",
        "diced bacon",
        "escalope",
        "gammon",
        "hog",
        "jowls",
        "knuckle",
        "ling - pig",
        "minced porc",
        "parma ham",
        "pieces of lard",
        "pig",
        "pig's cheek",
        "pig's ears",
        "piglet",
        "pigs trotter",
        "porc cheek",
        "pork belly",
        "soft fat",
        "pork filet",
        "pork foot",
        "pork head",
        "pork leg",
        "pork medallions",
        "pork riblet",
        "pork rump",
        "pork shoulder",
        "pork steak",
        "pork tenderloin",
        "pork - chop",
        "pork - cutlet",
        "rasher",
        "roast",
        "rump",
        "salt meat",
        "salted meat",
        "schnitzel",
        "schwarzwälder ham",
        "aerrano ham",
        "shank",
        "valentine steak",
        "andouille sausage",
        "andouillettes",
        "animal fat",
        "animal intestines",
        "atora",
        "banger",
        "beef marrow",
        "beef sausage",
        "black pudding",
        "blood pudding",
        "blood sausage",
        "boiling - meat",
        "bone",
        "bone marrow",
        "boneless",
        "bowels",
        "brats",
        "brawn",
        "cajun andouille",
        "cervelat",
        "charcuterie",
        "children's meatballs",
        "chitterlings",
        "chons",
        "chorizo sausage",
        "chump chop",
        "cold cuts",
        "cold meats",
        "collared beef",
        "collop",
        "confit",
        "cracklings",
        "cumberland sausage",
        "dripping pot",
        "dripping",
        "drippings",
        "escalope",
        "ewe",
        "faggot",
        "fat",
        "fat from roasted meat",
        "force meat balls",
        "frankfurter sausage",
        "frog's legs",
        "frying sausage",
        "galantine",
        "german sausage",
        "grease pot",
        "greaves",
        "grill sausages",
        "grilled sirloin of veal",
        "ground meat",
        "gurda",
        "hand and spring",
        "head cheese",
        "headmeat",
        "heart",
        "hind knuckle",
        "hindquarten",
        "horse rumpsteak",
        "horsemeat",
        "horsemeat sausage",
        "hotdogs",
        "continuation",
        "innards",
        "kaleji",
        "kidneys",
        "lard",
        "lardons",
        "leg",
        "liver",
        "liver paste",
        "liver paté",
        "liver sausage",
        "liverwurst",
        "louisiana boudin",
        "luncheon meat",
        "marbled meat",
        "meatloaf",
        "mince",
        "minced meat",
        "minced meat in a cover",
        "minced meat rolled in bacon",
        "moist",
        "mutton - beef sausages",
        "neck",
        "continuation",
        "noisette",
        "offal",
        "organ meats",
        "ox fat",
        "pâté spread",
        "patty",
        "continuation",
        "pepperoni",
        "pig snout",
        "pork caul",
        "pork sausage",
        "pork rind",
        "potted head",
        "quenelles",
        "continuation",
        "raw banger",
        "raw ham",
        "rissole",
        "rolled meat",
        "roulade",
        "salami sausage",
        "sausage rolls",
        "continuation",
        "saveloy",
        "scalded sausage",
        "shank",
        "shoarma meat",
        "shoulder",
        "sinews",
        "smoked beef",
        "continuation",
        "smoked sausage",
        "soup meat",
        "soupbone",
        "spleen",
        "streaky",
        "suet",
        "summer sausage",
        "continuation",
        "sweet peppers sausage",
        "swiss cut",
        "tallow",
        "tea wurst",
        "tewurst",
        "thigh",
        "continuation",
        "thinly pounded meat",
        "tongue",
        "tongue sausage",
        "top bit",
        "tripe",
        "turtle",
        "variety meats",
        "continuation",
        "veal olive",
        "white pudding"
    ]

    healthfood = [
        "apple",
        "apricot",
        "avocado",
        "banana",
        "berry",
        "blackberry",
        "blood orange",
        "blueberry",
        "boysenberry",
        "breadfruit",
        "cantaloupe",
        "cherry",
        "citron",
        "citrus",
        "coconut",
        "crabapple",
        "cranberry",
        "current",
        "date",
        "dragonfruit",
        "durian",
        "elderberry",
        "fig",
        "grape",
        "grapefruit",
        "guava",
        "honeydew",
        "jackfruit",
        "kiwi",
        "kumquat",
        "lemon",
        "lime",
        "lingonberry",
        "loquat",
        "lychee",
        "mandarin",
        "mango",
        "mangosteen",
        "marionberry",
        "melon",
        "mulberry",
        "nectarine",
        "orange",
        "papaya",
        "passion fruit",
        "peach",
        "pear",
        "persimmon",
        "pineapple",
        "plantain",
        "plum",
        "pluot",
        "pomegranite",
        "pomelo",
        "prune",
        "quince",
        "raisin",
        "rambutan",
        "raspberry",
        "starfruit",
        "strawberry",
        "tangelo",
        "tangerine",
        "ugli fruit",
        "watermelon",
        "amaranth",
        "barley",
        "bread",
        "brown rice",
        "buckwheat",
        "bulgur",
        "cornbread",
        "couscous",
        "crackers",
        "emmer",
        "farro",
        "flaxseed",
        "grano",
        "grits",
        "kamut grain",
        "millet",
        "oats",
        "oatmeal",
        "popcorn",
        "macaroni",
        "muesli",
        "noodles",
        "pitas",
        "pretzels",
        "quinoa",
        "rolled oats",
        "rice",
        "rye",
        "sorghum",
        "spaghetti",
        "spelt",
        "teff",
        "tortillas",
        "triticale",
        "whole grain",
        "wheat berries",
        "whole rye",
        "whole wheat",
        "wild rice",
        "acorn squash",
        "alfalfa",
        "artichoke",
        "arugula",
        "asparagus",
        "avocado",
        "bamboo shoots",
        "basil",
        "beans",
        "beets",
        "bell pepper",
        "black-eyed peas",
        "broccoli",
        "brussels sprouts",
        "capers",
        "carrot",
        "cauliflower",
        "celeriac",
        "celery",
        "chard",
        "chick peas",
        "chinese cabbage",
        "chives",
        "collard greens",
        "cress",
        "cucumber",
        "daikon",
        "dandelion greens",
        "eggplant",
        "endive",
        "fava bean",
        "fennel",
        "garlic",
        "ginger",
        "gourd",
        "greenbean",
        "greens",
        "hot chile peppers",
        "iceberg lettuce",
        "jicama",
        "kale",
        "kohlrabi",
        "leek",
        "lentils",
        "lettuce",
        "lima bean",
        "maize",
        "mung bean",
        "mushroom",
        "mustard greens",
        "okra",
        "olive",
        "onion",
        "parsley",
        "parsnip",
        "pattypan squash",
        "pea",
        "peapod",
        "peanut",
        "peppers",
        "pickle",
        "potato",
        "pumpkin",
        "radicchio",
        "radish",
        "rhubarb",
        "rocket",
        "romaine",
        "rutabaga",
        "salad",
        "salsa",
        "scallion",
        "seaweed",
        "shallot",
        "sorrel",
        "soybean",
        "spinach",
        "sprouts",
        "salsify",
        "spuds",
        "squash",
        "string bean",
        "succotash",
        "sweet potato",
        "swiss chard",
        "taro",
        "tomatillo",
        "tomato",
        "tuber",
        "turnip",
        "vegetable",
        "wasabi",
        "water chestnut",
        "watercress",
        "yam",
        "zucchini"

    ]
