---
# Show and retrieve all available Openstack images
- name: Retrieve all available Openstack images
  os_image_facts:

- name: Get image names and Ids
  set_fact:
    image_facts: "{{ image_facts|default([]) + [{'name': item.name, 'id': item.id}] }}"
  loop: '{{ openstack_image }}'
  loop_control:
    label: '{{ item.name }}'
  when: item.name is defined


